# wir brauchen die RBAC da der mongodb-community-operator noch nicht ausreichend auf verschiedenen Namespaces funktioniert. https://github.com/mongodb/helm-charts/issues/238#issuecomment-1717186162
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: fahrbar-common

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-database
  namespace: fahrbar-common
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-database
  namespace: fahrbar-common
subjects:
  - kind: ServiceAccount
    name: mongodb-database
roleRef:
  kind: Role
  name: mongodb-database
  apiGroup: rbac.authorization.k8s.io
