---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: community-operator-crds
  namespace: mongodb-kubernetes-operator
spec:
  chart:
    spec:
      chart: community-operator-crds
      version: ">=0.8.2"
      sourceRef:
        kind: HelmRepository
        name: mongodb-charts
        namespace: helmrepos
  interval: 1m0s
  targetNamespace: mongodb-kubernetes-operator
  releaseName: community-operator-crds
  install:
    createNamespace: false
    crds: "CreateReplace"
